// vite.frontend.config.ts
//
// Vite configuration for building the standalone SPA frontend.
// This produces a self-contained static site in frontend-dist/ that can be
// deployed to GitHub Pages (or any static host) independently of the Gitea
// Go binary.
//
// Usage:
//   pnpm exec vite build --config vite.frontend.config.ts
//
// With a custom default API server:
//   VITE_DEFAULT_API_URL=https://gitea.example.com \
//     pnpm exec vite build --config vite.frontend.config.ts

import {defineConfig} from 'vite';
import vuePlugin from '@vitejs/plugin-vue';
import {join} from 'node:path';
import tailwindcss from 'tailwindcss';
import tailwindConfig from './tailwind.config.ts';

export default defineConfig({
  // Root is the frontend/ directory so that index.html is treated as the
  // root-level file. Vite then outputs it flat to frontend-dist/index.html
  // (not the nested frontend-dist/frontend/index.html produced when root is
  // the project root). This is required so that the relative './assets/...'
  // references generated by base: './' resolve correctly at any deployment
  // sub-path without baking a fixed path into the bundle at build time.
  root: join(import.meta.dirname, 'frontend'),
  // './' keeps all asset URLs relative to the HTML file, so the bundle works
  // at any URL prefix (/, /gitea/, /my/sub/path/, …) at runtime.
  base: './',
  // Copy static assets (img/, fonts/) from the Go binary's public/assets
  // directory into the output.  This makes the site logo and other images
  // available without any server-side injection.  The files land at
  // frontend-dist/img/logo.svg etc., matching the `./img/logo.svg` URLs
  // produced by assetUrlPrefix='.' in spaconfig.ts.
  publicDir: join(import.meta.dirname, 'public/assets'),
  plugins: [
    vuePlugin({
      template: {
        compilerOptions: {
          // Keep parity with the main Vite config web-components list.
          isCustomElement: (tag) =>
            ['overflow-menu', 'relative-time', 'markdown-toolbar', 'text-expander'].includes(tag),
        },
      },
    }),
  ],
  css: {
    transformer: 'postcss',
    postcss: {plugins: [tailwindcss(tailwindConfig)]},
  },
  define: {
    __VUE_OPTIONS_API__: true,
    __VUE_PROD_DEVTOOLS__: false,
    __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: false,
  },
  build: {
    // outDir must be absolute when root is not the project root.
    outDir: join(import.meta.dirname, 'frontend-dist'),
    emptyOutDir: true,
    // No explicit rollupOptions.input: Vite auto-detects root/index.html.
  },
});
