name = "serverlesstea-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "serverlesstea"
database_id = "local-dev-db"

[[r2_buckets]]
binding = "GIT_BUCKET"
bucket_name = "serverlesstea-git"
